# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g @angular/cli
    - run: npm ci
    - run: ng build --prod --output-path docs --base-href /MoneyOderDasCalculator/
    - run: cd docs/
    - run: git init
    - run: git config user.name "WuMortal"
    - run: git config user.email "1170621609@qq.com"
    - run: git add .
    - run: git commit -m "push"
    - run: git push --force --quiet "https://${{ secrets.PUSH_TOKEN }}@${{ secrets.MoneyOderDasCalculator_ADDRESS }}" master:gh-pages
      env:
        CI: true
        
